import { Image } from "react-native";

// Define the interface for the store data
export interface Store {
  id: number;
  
  name: string;
  floor: string;  // Changed from 'description' to 'floor'
  localImage: string;
  screen: string;
  phone:string;
  description:string;
}

// Define the interface for all categories of stores
export interface Stores {
  [key: string]: Store[];
}

// The stores object containing all the store information
export const stores: Stores = {
  bakery: [
    { id: 1, name: "Bread Story", floor: "G22", localImage: require('./DetailsPages/PagesImg/BreadStory.png'), screen: 'BreadStory',phone:'03-77277155',description:'BreadStory make history on its most celebrated creations none other than the popular flossy buns carrying the names Flossy Signature, Flossy Hottie, Flossy Sponge, Flossy Twist, Lava Croissant, Magic Cheese Wand to Red Chamber and many more. One is never enough here!' },
    { id: 2, name: "Hogan Bakery", floor: "G26", localImage: require("./DetailsPages/PagesImg/HoganBakery.png"), screen: "HoganBakery",phone:'03-89530783',description:"Hogan's Bakery is a well-known bakery that specializes in a variety of fresh and delicious baked goods. They are particularly famous for their pastries, bread, and cakes, often made with high-quality ingredients. Hogan's Bakery typically offers a wide range of products, from classic options like croissants and sourdough bread to more creative and unique pastries. The bakery is popular for its commitment to quality, with many customers appreciating the freshness and flavor of their offerings. It's a go-to place for anyone looking for delightful baked treats." },
  ],
  beauty: [
    { id: 1, name: "Russell Salon", floor: "L152", localImage: require("./DetailsPages/PagesImg/RussellSalon.png"), screen: 'RussellSalon',phone:'03-77242828',description:"It's what you wear when you wear nothing else. It has to be good. It has to be you. It has to be done at J. Russell! The Salon. Short hair, long hair, making long hair short, or thanks to their hair extensions make short hair long. A new cut, a new color, its all possible in Russell Salon." },
    { id: 2, name: "The Nail Shop", floor: "G08", localImage: require("./DetailsPages/PagesImg/TheNailShop.png"), screen: 'TheNailShop' ,phone:'03-76214718',description:"Enjoy a classic manicure or relaxing pedicure at The Nail Shop. They offer the best styles and a relaxing atmosphere, and will keep you relaxed and looking your best. Their committed and competent team will be sure to keep your nails healthy and beautiful."},
    { id: 3, name: "AsterSpring", floor: "G16", localImage: require("./DetailsPages/PagesImg/AsterSpring.png"), screen: 'AsterSpring',phone:'03-77262433',description:"AsterSpring is a leading chain of professional skincare salons and kiosks in ASEAN and Hong Kong. We combine the expertise of our highly trained and certified professional skincare therapists with advanced technology and world-leading products to provide effective, safe, and personalized solutions for you. Having treated more than 10 million faces since 1984, we are committed to your GreatSkinHealth, promising optimal results one face at a time." },
  ],
  books: [
    { id: 1, name: "Popular", floor: "L150", localImage: require("./DetailsPages/PagesImg/Popular.png"), screen: 'Popular' ,phone:'03-77225416',description:"Established in January 1984, POPULAR Book Co.(Malaysia) Sdn.Bhd.has become a household name in Malaysia and has now grown to more than 93 stores nationwide.It is recognised and listed by the Malaysian Book of Records as the largest bookstore chain in Malaysia, with over 780,000 square feet of retail space. POPULAR Book Co.(Malaysia) Sdn. Bhd. is 100% managed by Malaysians and is strongly positioned as a trilingual one-stop bookstore catering for everyone from all walks of life.POPULAR sells a wide variety of fiction, non-fiction and general interest books in English, Chinese and Malay languages, as well as school textbooks and revision books. In addition, it also offers a large selection of magazines, stationery, multi-media products, gift items and CDs. For more information, visit www.popularworld.com/about/story.html"},
    { id: 2, name: "Pop Mart", floor: "L169", localImage: require("./DetailsPages/PagesImg/PopMart.png"), screen: 'PopMart',phone:'03-27228882',description:"Pop Mart is a trendy retail store specializing in collectible designer toys and blind box figures. Known for its creative and unique designs, Pop Mart offers a wide range of characters that appeal to fans of all ages. Visitors can explore the latest collections, discover limited-edition items, and enjoy the thrill of unboxing surprises. Pop Mart is a must-visit destination for anyone looking for fun, artistic, and highly collectible toys within the mall." },
    { id: 3, name: "Balloon Wonderland Part Shop", floor: "L175", localImage: require("./DetailsPages/PagesImg/Balloon.png"), screen: "Balloon" ,phone:'03-7710 3827',description:"Balloon Wonderland is your one stop shop for all your balloons and party requirements. We stock the large range of party supplies including helium balloons, Themed Party decorations, birthday candles, seasonal merchandise, costumes and etc. With our unique products and specialized service, we help people to create amazing parties"},
  ],
  department: [
    { id: 1, name: "Aeon1", floor: "G80", localImage: require("./DetailsPages/PagesImg/Aeon.png"), screen: 'Aeon1',phone:'03-77221327',description: "Probably the most well-known store and is well established among Malaysians as well as foreigners, under one roof where you get to find all sorts of items ranging from fashion, home, electrical items to groceries shopping. This is our prinsiple regardless of any changed, is to serve the Customer First."},
    { id: 2, name: "Aeon2", floor: "L180", localImage: require("./DetailsPages/PagesImg/Aeon.png"), screen: 'Aeon2',phone:'03-77221327',description: "Probably the most well-known store and is well established among Malaysians as well as foreigners, under one roof where you get to find all sorts of items ranging from fashion, home, electrical items to groceries shopping. This is our prinsiple regardless of any changed, is to serve the Customer First."},
  ],
  digital: [
    { id: 2, name: "Samsung", floor: "L166", localImage: require("./DetailsPages/PagesImg/Samsung.png"), screen: 'Samsung',phone:'03-7726 8098',description: "Flagship Samsung Store that offers repairs and a view into the world of Samsung. The store where you can view and experience the latest phone and gadgets offered by Samsung. Staff is pretty friendly and helpful. Overall is a nice place to visit even if you're not repairing your phone and are a Samsung fan or just curious."},
    { id: 4, name: "Vivo", floor: "G39", localImage: require("./DetailsPages/PagesImg/Vivo.png"), screen: 'Vivo',phone:'017-357 9992',description: "Our product’s camera also represents one of our most important competitive advantages. Photography is a way for people to express themselves and share joy with others. Through our smartphones, we offer users a professional-grade photography solution, taking mobile photography to the level of an art form, witnessing and recording all of life’s beautiful moments."},
  ],
  enrichment: [
    { id: 1, name: "Box Hunt", floor: "L170", localImage: require("./DetailsPages/PagesImg/BoxHunt.png"), screen: "BoxHunt",phone:'013-33445566',description: "Box hunt is a chain store retailer specializing in blind boxes and all sort of toys and figures"},
    { id: 2, name: "Gamer's Hideout", floor: "L168", localImage: require("./DetailsPages/PagesImg/GamersHideout.png"), screen: "Gamer'sHideout",phone:'03-7727 2775',description: "Gamers Hideout is committed to offer the best entertainment experience for all ages while simultaneously giving the best retail experience for their customers. The company is also committed to providing the best and latest in entertainment products and services which caters to the avid Malaysian gamer."},
    { id: 3, name: "Yamaha Music", floor: "G36", localImage: require("./DetailsPages/PagesImg/YamahaMusic.png"), screen: "YamahaMusic",phone:'019-216 3288',description: "Yamaha Corporation is a Japanese multinational corporation and conglomerate with a very wide range of products and services. It is one of the constituents of Nikkei 225 and is the world's largest musical instrument manufacturing company. Providing music education and musical instruments such as pianos, portable keyboards, drums, guitars, synthesizers, brass & woodwinds, as well as home audio ."},
  ],
  fashion: [
    { id: 1, name: "Cheetah", floor: "L160", localImage: require("./DetailsPages/PagesImg/Cheetah.png"), screen: "Cheetah",phone:'03-7726 9819',description: "The CHEETAH brand was launched in 1979. Since then, the company – Cheetah Corporation (M) Sdn Bhd has grown over the years and more categories to include ladies, children, baby and life-styled casual wears under labels – Cheetah Ladies, Cheetah Junior, C.Union, C2 United, CTH Unlimited, Baby Cheetah and Arissa.In addition, the company has two international Licensing brand – Ladybird and GQ. And it has an Exclusive Licensee contract with Focus Point Eyewear for eyewear frames."},
    { id: 2, name: "Cotton On", floor: "L151", localImage: require("./DetailsPages/PagesImg/CottonOn.png"), screen: "CottonOn",phone:'03-7733 4930',description: "BORN IN 1991, COTTON ON DELIVERS VALUE FASHION AND QUALITY BASICS DESIGNED TO EXCEED OUR CUSTOMER’S EXPECTATIONS. We are a focused, passionate and hands-on brand with a single focus: to deliver on-trend basics and fast, fun fashion, all while making sure we're having some fun doing it.Cotton On’s product offering includes womenswear, menswear and accessories as well as elevated apparel range CO by Cotton On."},
    { id: 3, name: "FOS", floor: "L163", localImage: require("./DetailsPages/PagesImg/FOS.png"), screen: "FOS",phone:'012-718 8565',description: "F.O.S is an established clothing retail chain and value fashion in South East Asia that specializes in affordable quality apparel. Graphic tees, polo tees, shirts, denim, bottoms, accessories, basic wear, footwear, and more - If it's a fashion staple must-have, we'll carry it! Find it, Love it, Buy it for Less at F.O.S!"},
    { id: 4, name: "H&M", floor: "L153", localImage: require("./DetailsPages/PagesImg/HnM.png"), screen: "H&M",phone:'03-7722 1397',description:"Founded in 1947, H&M is a global fashion brand and pioneer of design collaborations with style icons such as Karl Lagerfeld, Stella McCartney, Viktor & Rolf, Roberto Cavalli, Comme des Garçons, Sonia Rykiel and Lanvin."},
    { id: 5, name: "Levi'Store", floor: "L158", localImage: require("./DetailsPages/PagesImg/LevisStore.png"), screen: "Levi'sStore",phone:'03-7732 6130',description: "Created in 1873, Levi's® jeans are the original, authentic jeans. As the inventor of the category, the Levi's® brand continues to define jeanswear with the widest range of products available, from quintessential classics such as the famous Levi's® 501® Original jean, to favourite fits and styles in the Red Tab™ and premium collections."},
    { id: 6, name: "Uniqlo", floor: "L164", localImage: require("./DetailsPages/PagesImg/Uniqlo.png"), screen: "Uniqlo" ,phone:'03-6421 9278',description:"Shop stylish and comfortable clothes for women, men, kids and babies. Fashionable and perfect for every season with groundbreaking technology."},
  ],
  food: [
    { id: 1, name: "KFC", floor: "G37", localImage: require("./DetailsPages/PagesImg/KFC.png"), screen: "KFC" ,phone:'03-7890 0697',description:"KFC is is an American fast food restaurant chain that specializes in fried chicken which is pressure fried chicken pieces, seasoned with Sanders' recipe of 11 herbs and spices. They also serves rice, burgers,wraps, as well as salads and side dishes, such as French fries and coleslaw, desserts, and soft drinks."},
    { id: 2, name: "Burger King", floor: "G30", localImage: require("./DetailsPages/PagesImg/BurgerKing.png"), screen: "BurgerKing",phone:'03-7613 8278',description: "Knowing for serving high-quality, great tasting and affordable food. Try and enjoy the great and healthy flame-grilled taste of Burger King products."},
    { id: 3, name: "Mc Donalds", floor: "G01", localImage: require("./DetailsPages/PagesImg/McDonalds.png"), screen: "McDonalds",phone:'03-7621 5831',description: "McDonald's are fast food restaurant featuring value-priced food and well known for their burgers, chicken products, french fries, breakfast items, soft drinks, milkshakes, wraps, and desserts."},
    { id: 4, name: "BIBI's Popiah", floor: "G06", localImage: require("./DetailsPages/PagesImg/BIBI.png"), screen: "BIBI" ,phone:'017-3413844',description:"Well-loved local popiah located in Restaurant Kam Wan Ipoh made with fresh ingredients, juicy turnips and crispy crumbs!"},
    { id: 5, name: "Kenny Rogers Roaster", floor: "L153", localImage: require("./DetailsPages/PagesImg/KRR.png"), screen: "KRR" ,phone:'03-7732 0347',description:"Kenny Rogers Roasters is a chain of chicken-based restaurants. At the heart of every great roast chicken is a great marinade. The secret of their great taste is signature blend of lemon, ginger, sage and oregano (the rest of the ingredients are of course, a secret)."},
    { id: 6, name: "Secret Recipe", floor: "G19", localImage: require("./DetailsPages/PagesImg/SecretRecipe.png"), screen: "SecretRecipe",phone:'03-7726 7499',description: "Secret Recipe renowned for its extensive range of fine quality gourmet cakes. It has since evolved to become one of the fastest growing lifestyle cakes and café chain in the region with over 440 café outlets to date."},
    { id: 7, name: "Seoul Garden", floor: "G43", localImage: require("./DetailsPages/PagesImg/SeoulGarden.png"), screen: "SeoulGarden",phone:'03-7722 1339',description: "Serving Asian Korean-styled cuisine in a buffet-styled format at very affordable prices with good varieties of seafood, marinated meats, namul and vegetables. The idea of Seoul Garden is to grow the brand in tandem with the customers – from student years to working adults to starting a family."},
    { id: 8, name: "StarBucks", floor: "G45", localImage: require("./DetailsPages/PagesImg/StarBucks.png"),screen: "StarBucks" ,phone:'03-7496 8637',description:"At Starbucks, it is always more than just a cup of coffee. Create meaningful connections within its relaxing environment with comfortable chairs and complimentary WiFi, while the friendly baristas handcraft a cup of your favorite Starbucks beverage that's just right for you."},
    { id: 9, name: "Sushi King", floor: "G28", localImage: require("./DetailsPages/PagesImg/SushiKing.png"), screen: "SushiKing",phone:'03-7731 0415',description: "Sushi King chain of restaurants serves quality sushi and other Japanese cuisine at affordable prices in a warm and friendly environment. What sets Sushi King apart is the personal touch of serving freshly made sushi on the kaiten for customers to pick up and enjoy."},
  ],
  foodcourt: [
    { id: 1, name: "Food District", floor: "L177", localImage: require("./DetailsPages/PagesImg/FoodDistrict.png"), screen: "FoodDistrict" ,phone:'014-320 6894',description:"Food District serves crave-worthy Malaysian rice platters to comforting Asian noodle bowls, Japanese Teppanyaki to Arabian Shawarma and even Artisanal Coffee."},
  ],
  entertainment: [
    { id: 1, name: "TGV Cinemas", floor: "L283", localImage: require("./DetailsPages/PagesImg/TGV.png"), screen: "TGV",phone:'03-7722 2717',description:"We strive to improve every day to ensure our customers have the best time and leave with fond memories only to return for more exciting cinematic experience. We have a dedicated team behind these screens who are committed to make you smile! We refurbished some of our flagship locations to give it a fresh look, mainly to adopt a more welcoming, vibrant, contemporary ambiance. Some of the cinema halls were redesigned and renovated to maximise the space. Aside from the facelift, TGV Cinemas is 100% digital. Cinema-goers can enjoy unmatched brightness, sharpness and superior images in high definition contents such as films, documentaries and other alternative content in superior quality. Not forgetting, our signature caramel popcorns is delicious. A regular popcorn is never enough, you will crave for more, don’t say we didn’t warn you!" },
    { id: 2, name: "Karaoke Manekineko", floor: "L282", localImage: require("./DetailsPages/PagesImg/Karaoke.png"), screen: "Karaoke",phone:'03-2181 3242',description:"Experience pocket friendly and fun singing session with fully furnished vibrant and trendy rooms with various capacity and be refreshed with a variety of free flow of drinks and snacks at the self-service bar." },
  ],
  health: [
    { id: 1, name: "GINTELL", floor: "G14", localImage: require("./DetailsPages/PagesImg/GINTELL.png"), screen: "GINTELL",phone:'03-9779 6989',description:"Everyone needs some tender loving care at home, and Gintell is a brand that can provide it! A household name in comfort, Gintell’s strength lies in its range of reliable massage and fitness equipment. Each sturdy massage chair offers a pleasurable, relaxing sensation that will take all your day’s worries away. Head over there and experience it for yourself!" },
    { id: 2, name: "Guardian", floor: "G34", localImage: require("./DetailsPages/PagesImg/Guardian.png"), screen: "Guardian",phone:'03-7726 1916',description: "Guardian is the leading Pharmacy, Health and Beauty chain in Malaysia. The strong branding, extensive range of health and beauty products and their customer-driven focus approach have enabled them to maintain their position at the top of the market."},
    { id: 3, name: "Watson", floor: "L171", localImage: require("./DetailsPages/PagesImg/Watsons.png"), screen: "Watson",phone:'03-7496 7059',description: "Watson is Asia 's leading health and beauty retailer. They continually sets the standards in the health, wellness and beauty market, providing personalised advise and counselling on the top its market-leadig product range."},
  ],
  lifestyle: [
    { id: 1, name: "Daiso", floor: "L176", localImage: require("./DetailsPages/PagesImg/Daiso.png"), screen: "Daiso",phone:'03-3010 2294',description:"Daiso Industries Co., Ltd. is a large franchise of 100-yen shops founded in Japan. Its headquarters are in Higashihiroshima, Hiroshima Prefecture. Daiso has a range of over 100,000 products, many made in China or South Korea, focusing on household items such as kitchenware and cleaning products." },
    { id: 2, name: "MR DIY", floor: "L165", localImage: require("./DetailsPages/PagesImg/MrDIY.png"), screen: "MRDIY",phone:'03-7732 0661',description: "MR.DIY, sometimes stylised as MR.D.I.Y., is a home improvement retailer owned by Malaysian company Mr D.I.Y. Group Berhad. It offers home improvement products for do-it-yourself through its network of shops and online stores"},
  ],
  convienience: [
    { id: 1, name: "MyNews", floor: "G21", localImage: require("./DetailsPages/PagesImg/MyNews.png"), screen: "MyNews",phone:'03-7722 2251',description:"myNEWS.com is a contemporary and friendly store with the widest selection of convenience and print products that meet your needs and expectations." },
    { id: 2, name: "MixStore", floor: "G41", localImage: require("./DetailsPages/PagesImg/MixStore.png"), screen: "MixStore" ,phone:'03-7613 3103',description:"Discover the trendiest and latest products around the world at our store."},
    { id: 3, name: "CU", floor: "G03", localImage: require("./DetailsPages/PagesImg/CU.png"), screen: "CU",phone:'012-358 2663',description: "CU is a popular convenience store chain originating from South Korea. Known for its wide variety of products, CU offers everything from snacks, beverages, and ready-to-eat meals to household essentials and personal care items. The stores are typically open 24/7, making them a convenient stop for quick purchases at any time of day."},
  ],
  snacks: [
    { id: 1, name: "Baskin Robbins", floor: "L178", localImage: require("./DetailsPages/PagesImg/BaskinRobbin.png"), screen: "BaskinRobbins",phone:'03-7665 1931',description: "Baskin-Robbins offers over 1,000 flavors of ice cream, including Sugar Free, Fat Free and Light. Their menu also includes frozen yogurt, sorbets, sherbets, beverages, cakes, sundaes and handpacked for every occasion !"},
    { id: 2, name: "Bee Cheng Hiang", floor: "G07", localImage: require("./DetailsPages/PagesImg/BeeChengHiang.png"), screen: "BeeChengHiang",phone:'03-7725 1306',description:"Bee Cheng Hiang is a one-stop centre for a wide range of bakkwa (meat jerky), meat floss and other non-halal delicacies that makes festive reunions & other celebrations complete and memorable. With commitment closing to a century, Bee Cheng Hiang boast pride in assuring that their products are made of 100% natural premium ingredients; with NO added MSG, NO added meat tenderisers, NO added preservatives & NO artificial colouring." },
    { id: 3, name: "Inside Scoop", floor: "G05", localImage: require("./DetailsPages/PagesImg/InsideScoop.png"), screen: "InsideScoop",phone:'03-7622 1735',description: "Inside Scoop is a homegrown success story; an artisanal creamery churning ice cream from scratch in small batches. Their handcrafted creations bear the markings of the freshest ingredients expertly curated without artificial flavouring or preservatives. With more than 60 flavours presented on rotation, popular flavours range from classics such as Valrhona Chocolate and Pistachio, to local darlings such as Cempedak, Teh Tarik and Durian made with real durian flesh from Raub, Pahang. Come try their delectable crunchy waffles and ice cream cakes too. Always remember, anytime is a good time for ice cream."},
  ],
  sports: [
    { id: 1, name: "ADIDAS", floor: "G42", localImage: require("./DetailsPages/PagesImg/ADIDAS.png"), screen: "ADIDAS",phone:'03-7710 0094',description: "Adidas is one of the largest athletic apparel and footwear corporation in the world. Adidas offers you to enjoy the freshest new shoes, clothing, activewear, sportswear styles and more."},
    { id: 2, name: "NIKE", floor: "L161", localImage: require("./DetailsPages/PagesImg/NIKE.png"), screen: "NIKE",phone:'03-7725 4035',description: "Nike offers a wide range of products, including running shoes, basketball sneakers, workout gear, and lifestyle apparel. The brand collaborates with top athletes and designers to create both functional and fashionable items. Whether you're looking for the latest in athletic technology or stylish sportswear, Nike is a top destination for quality and performance."},
    { id: 3, name: "Decathlon", floor: "L174", localImage: require("./DetailsPages/PagesImg/Decathlon.png"), screen: "Decathlon" ,phone:'03-7732 9221',description:"Discover the ultimate sports haven at Decathlon 1 Utama – where accessibility meets adrenaline. Our dedicated team of 51 enthusiasts is poised to serve you with unmatched passion and expertise. Unleash the power of sport with us – where every step is a leap towards a healthier, happier you!"},
  ],
};
